### ISSUE TITLE
Criação de Currículo Lattes

### ISSUE THREAD

**Issue by FabricaAppU9** [FabricaAppU9/Espirometria#15]

**Comment by matheusopedro** [comment]
Link para cadastro do Currículo Lattes no CNPq:
https://wwws.cnpq.br/cvlattesweb/pkg_cv_estr.inicio

**Comment by GuilhermeFujita** [comment]
http://lattes.cnpq.br/8799982238613036

**Comment by BiancaArantes28** [comment]
http://lattes.cnpq.br/4463658851358783

**Comment by MarcelaMenezes** [comment]
http://lattes.cnpq.br/4142614181469254

**Comment by josejuniorcj** [comment]
http://lattes.cnpq.br/3517624388923797
