### ISSUE TITLE
Criação do Perfil no Linkedin

### ISSUE THREAD

**Issue by FabricaAppU9** [FabricaAppU9/Espirometria#17]

**Comment by FabricaAppU9** [comment]
Vamos todos criar o perfil no Linkedin para podermos associar todos ao Projeto que vai ser mencionado lá.

**Comment by josejuniorcj** [comment]
Quem já tem, onde disponibilizar o link?

**Comment by FabricaAppU9** [comment]
Pessoal, Vocês podem adicionar a URL do seu perfil aqui.

**Comment by leonardo-sguimaraes** [comment]
https://www.linkedin.com/in/leonardo-guimar%C3%A3es-99b693b3?trk=nav_responsive_tab_profile

**Comment by matheusopedro** [comment]
https://br.linkedin.com/in/matheuspedro

**Comment by GuilhermeGolfetto** [comment]
https://br.linkedin.com/in/guilhermegolfetto

**Comment by GuilhermeFujita** [comment]
https://br.linkedin.com/in/guilherme-sant-ana-fujita-5b49b0114

**Comment by josejuniorcj** [comment]
https://www.linkedin.com/in/jos%C3%A9-j%C3%BAnior-08931144?trk=nav_responsive_tab_profile_pic

**Comment by vanessapereira** [comment]
Perfil público https://br.linkedin.com/in/vanessa-pereira-94011353

**Comment by BiancaArantes28** [comment]
https://www.linkedin.com/in/bianca-arantes-dos-santos-919744121?trk=nav_responsive_tab_profile

**Comment by Shinoda00** [comment]
https://www.linkedin.com/in/alexandre-correa-alves-4aa5ab9b?trk=nav_responsive_tab_profile

**Comment by MarcelaMenezes** [comment]
https://br.linkedin.com/in/marcela-menezes-17a71964

**Comment by MathJosh** [comment]
https://www.linkedin.com/in/matheus-silva-sousa-717a5b103?trk=nav_responsive_tab_profile_pic

**Comment by JonathanP157** [comment]
https://www.linkedin.com/in/jonathan-de-paulo-souza-3bb935125?trk=nav_responsive_tab_profile
