### ISSUE TITLE
Criar questionário com dúvidas sobre o projeto

### ISSUE THREAD

**Issue by FabricaAppU9** [FabricaAppU9/Espirometria#19]
Vanessa, creio que você está com as perguntas, certo?

**Comment by vanessapereira** [comment]
Sim, estou com as perguntas, vou coloca-las aqui para que todos saibam e se tiverem mais alguma coisa pra discutir e acrescentar é só informar.

**Comment by vanessapereira** [comment]
Pessoal, o questionário foi compartilhado no google drive. Caso alguém tenha mais alguma dúvida me enviem ou podem editar.
