### ISSUE TITLE
Estudo AspNet Core (MVC 5)

### ISSUE THREAD

**Issue by vanessapereira** [FabricaAppU9/Espirometria#22]
Entity_Framework

**Comment by FabricaAppU9** [comment]
https://www.youtube.com/channel/UCf38XAdgw1I1uh5OrVfhZZg

**Comment by gabrielbaptista** [comment]
https://drive.google.com/file/d/0B4k1tI2kAFbPNnI4Q1JfUVZacjQ/view?usp=sharing
