### ISSUE TITLE
Revisão - Caso de Uso 03 – Calcular

### ISSUE THREAD

**Issue by FabricaAppU9** [FabricaAppU9/Espirometria#32]

**Comment by Shinoda00** [comment]
Enviarei um e-mail aos professores para levantarmos "traduções" mais completas das abreviações, pois temos muitas variações de resultados para a mesma sigla e ou temos siglas diferentes para o mesmo resultado baseando-se na formula que foi usada para chegar ao resultado.

**Comment by Shinoda00** [comment]
Tarefa finalizada e revisada junto ao prof Gabriel.
