### ISSUE TITLE
Dev - Implementação Pacote Model

### ISSUE THREAD

**Issue by jsoft-ti** [FabricaAppU9/Espirometria#35]
br.com.uninove.fabricaapp.espirometria.model

**Comment by josejuniorcj** [comment]
Pacote Criado.

**Comment by leonardo-sguimaraes** [comment]
Alteração no caso de uso.

Atributos da classe  "Pessoa"  do pacote model: 
- altura:  int -> double;
- massa int -> double; 
- sexo int -> char;

**Comment by josejuniorcj** [comment]
Após alteração, pacote atualizado.
