### ISSUE TITLE
Dev - Definir os valores de entrada e resultados esperados em relação aos cálculos

### ISSUE THREAD

**Issue by jsoft-ti** [FabricaAppU9/Espirometria#37]

**Comment by GuilhermeFujita** [comment]
Na planilha com os cálculos, não foi possível calcular o PFE, pois este não se encontra presente no código em VB e consequentemente fora do código Java
Para os cálculos foi estabelecido o peso de 60 kg tanto para o masculino quanto para o feminino, sendo que, para o masculino, não havia influência deste nos cálculos, já no feminino sim, esse peso foi adotado por ser o peso médio para o sexo feminino.
