### ISSUE TITLE
Apresentação - Fábrica

### ISSUE THREAD

**Issue by gabrielbaptista** [FabricaAppU9/Espirometria#57]

**Comment by FabricaAppU9** [comment]
Vanessa, estudar a possibilidade de utilizar o próprio site como apresentação.

**Comment by FabricaAppU9** [comment]
Vanessa, utilize essa referência
https://github.com/FabricaAppU9/SiteOficial/wiki/Mapa-do-Site-Sugerido

**Comment by FabricaAppU9** [comment]
Vamos levar o tema: "Projeto de Extensão Experimental: Fábrica de Apps da UNINOVE – Que tal transformar boas ideias em realidade?" A ideia é incentivar alunos de nossa área a se interessar pela fábrica e acreditamos que vamos conseguir um grande número de alunos nesse dia. Já estamos nos preparando para organizar esse cadastro através de nosso site.

**Comment by FabricaAppU9** [comment]
Vanessa, qual é o status da apresentação?

**Comment by Deborauni9** [comment]
Muito bom. Vamos expandir no próximo semestre.
