### ISSUE TITLE
Informe de "Faixas limites" Não está exibindo em tabela

### ISSUE THREAD

**Issue by danielerodrigues** [FabricaAppU9/Espirometria#66]
Passos pra reproduzir: Acionar o campo "Faixas Limites".

Verifique o comportamento: Os dados não está exibindo em tabela.

Resultado esperado: O sistema abre a área “Faixa Limite” com a tabela com as faixas limite separadas por gênero.

**Comment by josejuniorcj** [comment]
Como esse relato não é impeditivo para o funcionamento do software, não se aplica.
