### ISSUE TITLE
Travar a tela do app na posição Vertical

### ISSUE THREAD

**Issue by danielerodrigues** [FabricaAppU9/Espirometria#76]
Ao deixar o celular na posição horizontal e acionar a opção idade o Layout quebra.

Passos para reproduzir: Posicionar o celular na horizontal> acionar o campo idade> Verifique o comportamento.

Resultado Esperado: Travar o app deixar somente na posição Vertical.

**Comment by BiancaArantes28** [comment]
Já foi feito isso hoje, no celular a tela está travada na vertical e no tablet na horizontal.
