### ISSUE TITLE
Estudar Progressive WebApps

### ISSUE THREAD

**Issue by FabricaAppU9** [FabricaAppU9/Espirometria#92]

**Comment by FabricaAppU9** [comment]
Gostaria de um relatório de cada um sobre esse assunto

**Comment by josejuniorcj** [comment]
Galera, Slides da palestra de Sérgio Lopes na RubyConf Brazil da Caelum: 
http://www.slideshare.net/caelumdev/progressive-web-apps-o-melhor-da-web-appficada

**Comment by josejuniorcj** [comment]
Material legal tb sobre o assunto: 
http://www.matera.com/br/2016/10/03/progressive-web-apps-a-web-turbinada/

**Comment by josejuniorcj** [comment]
Canal do Chrome no Youtube sobre Web Apps:
https://www.youtube.com/playlist?list=PLNYkxOF6rcIAWWNR_Q6eLPhsyx6VvYjVb

**Comment by GolfettoGuilherme** [comment]
Um Podcast sobre Progressive Web Apps
http://bit.ly/2fRlzQU
