### ISSUE TITLE
Criar Wiki do Projeto

### ISSUE THREAD

**Issue by vanessapereira** [FabricaAppU9/Espirometria#93]

**Comment by FabricaAppU9** [comment]
Matheus,

Qual o status dessa tarefa?

**Comment by josejuniorcj** [comment]
Posso Participar?

**Comment by matheusopedro** [comment]
Pode, ainda não comecei, o Wiki vai ser feito no próprio Git.
Pode começar montando uma estrutura para aprovação do pessoal

Em 21/11/2016 19:18, "josejuniorcj" notifications@github.com escreveu:

**Comment by FabricaAppU9** [comment]
Claro!

**Comment by josejuniorcj** [comment]
Beleza Matheus, vamos nos falando então :)

**Comment by josejuniorcj** [comment]
Hm.. Matheus, já ouviu falar no Gogs? Acho que isso pode nos ajudar. 
Dar uma olhada ai: https://fjorgemota.com/gogs-um-sistema-versatil-para-hospedagem-de-repositorios-git/

**Comment by matheusopedro** [comment]
Criei uma página na wiki desse repositório, pra ver como funciona.

https://github.com/FabricaAppU9/Espirometria/wiki/Base-de-Conhecimento---Adicionado-%C3%ADcones-do-menu

Podemos ir adicionando as páginas já.

**Comment by jsoft-ti** [comment]
Acho que essa tarefa é contínua, não sei se faz sentido deixar aberta aqui.
