### ISSUE TITLE
Reformular Caso de USO

### ISSUE THREAD

**Issue by Shinoda00** [FabricaAppU9/Espirometria#95]
Trazer melhorias para os casos de usos, focar na melhor forma de armazenamento dos dados e detalhar melhor as atividades dentro dos casos.

**Comment by FabricaAppU9** [comment]
Qual é o status dessa revisão, Alexandre?

**Comment by Shinoda00** [comment]
Feita, porém estou aguardando o feedback dos devs, para ajustarmos qualquer mudança necessária.

**Comment by Shinoda00** [comment]
Fechando a ISSUE
