### ISSUE TITLE
Deixe seu Gmail aqui para Participar da nossa Agenda de Eventos! (Se possível, deixe o gmail de quem está no Git tb)

### ISSUE THREAD

**Issue by josejuniorcj** [FabricaAppU9/Espirometria#96]

**Comment by GuilhermeFujita** [comment]
fujitaguilherme@gmail.com

**Comment by matheusopedro** [comment]
matheusinaciopedro@gmail.com
Em 30/10/2016 08:19, "Guilherme Fujita" notifications@github.com escreveu:

**Comment by gabrielbaptista** [comment]
gabriel.l.baptista@gmail.com
gabriel.baptista@uni9.pro.br

**Comment by danielerodrigues** [comment]
danielelut26@gmail.com

**Comment by BiancaArantes28** [comment]
biancaarantes28@gmail.com

**Comment by raphaelzr** [comment]
raphaelzilligr@gmail.com

---

De: josejuniorcj notifications@github.com
Enviado: domingo, 30 de outubro de 2016 18:42
Para: FabricaAppU9/Espirometria
Cc: Raphaelzr; Mention
Assunto: Re: [FabricaAppU9/Espirometria] Deixe seu Gmail aqui para Participar da nossa Agenda de Eventos! (Se possível, deixe o gmail de quem está no Git tb) (#96)

Assigned #96https://github.com/FabricaAppU9/Espirometria/issues/96 to @Raphaelzrhttps://github.com/Raphaelzr.

##

**Comment by vanessapereira** [comment]
vanesssapereira@gmail.com

**Comment by leonardo-sguimaraes** [comment]
leo.leo.gui70@gmail.com

**Comment by ricardohenrique** [comment]
ricardohenriquebm@gmail.com

**Comment by Deborauni9** [comment]
debora.canne@gmail.com
