### ISSUE TITLE
Correção do texto no site

### ISSUE THREAD

**Issue by Shinoda00** [FabricaAppU9/Espirometria#97]
Pessoal, no site da fabrica tem um trecho de texto que esta com um pequeno erro de concordância conforme o arquivo no anexo ou link abaixo.
![captura de tela de 2016-11-05 15-06-41](https://cloud.githubusercontent.com/assets/19504016/20032061/8b6aaac4-a369-11e6-8a25-345f2c451d5d.png)

**Comment by FabricaAppU9** [comment]
Alexandre,

Temos o local para postar isso no Projeto de Sites:
https://github.com/FabricaAppU9/SiteOficial/invitations

Coloque essa issue lá, ok?

O seu convite de participação está aberto.

**Comment by Deborauni9** [comment]
Já  foi arrumado o texto  do site?
