### ISSUE TITLE
Limite VEF e FEF estão resultando sempre 0

### ISSUE THREAD

**Issue by FabricaAppU9** [FabricaAppU9/Espirometria#98]
Verificar bug na última versão

**Comment by FabricaAppU9** [comment]
Pessoal,

Esse é um bug. Precisamos corrigir.

**Comment by Deborauni9** [comment]
Já  fizeram o teste para ver se o Bug  foi corrigido?

**Comment by danielerodrigues** [comment]
Realizei o teste na versão v1.7.3 o erro persiste

**Comment by josejuniorcj** [comment]
Análise do erro em andamento. 
@danielerodrigues não fora liberado nenhuma versão para teste indicando que esse erro foi corrigido.

**Comment by danielerodrigues** [comment]
Ok

Em 21 de nov de 2016 6:15 PM, "josejuniorcj" notifications@github.com
escreveu:

**Comment by GolfettoGuilherme** [comment]
Corrigido !!!

Alterado calculo do VEF/FEF inferior - (idade maior que 14)

Resolvido problema no calculo de CV, corrigido problema de digitação  por motivos desconhecidos

Valores Validados em relação ao Pro Calc
