### ISSUE TITLE
Estudar novo cálculo - Pro Calc

### ISSUE THREAD

**Issue by FabricaAppU9** [FabricaAppU9/Espirometria#99]
Leo / Júnior,

Vocês vão conduzir essa tarefa que é importantíssima. 

Gostaria que analisassem os novos parâmetros enviados pelo professor Nacif:
https://drive.google.com/drive/folders/0B4k1tI2kAFbPYjItWTlydlpSSVE?usp=sharing

E tentassem revisar a nossa documentação 
https://drive.google.com/open?id=1yxZjeqJ-QvOmcpZFsZshTk7N6ZxFpbvqOMUQTYlg3JQ

Falem comigo assim que lerem esse material.

**Comment by Deborauni9** [comment]
Golfetto você  verificou o problema de arredondamento ou foi o Ale?

**Comment by Deborauni9** [comment]
Novos cálculos estudados.
Separar as funções lineares e logaritmicas

**Comment by GolfettoGuilherme** [comment]
Implementado novos cálculos no porém. existe uma divergência para com o calculo de FEF 25-75 onde o resultado está negativo, ficamos de verificar com o Professor Nacif.

**Comment by FabricaAppU9** [comment]
Pessoal,

Reabri e deixei essa questão para ser resolvida na visita ao professor Nacif.
